hungerzero/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static 
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('zerowaste.urls')),
    path('admin/', admin.site.urls),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='zerowaste/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="zerowaste/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='zerowaste/password_reset_complete.html'), name='password_reset_complete'),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zerowaste/urls.py
from unicodedata import name
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import login, logout
from django.contrib.auth import views as auth_views
from . import views

app_name = 'zerowaste'

urlpatterns = [
    path('index', views.ListView.as_view(), name='index'),
    path('add/', views.CreateView.as_view(), name='add'),
    path('create_account/', views.create_account, name='create_account'), 
    path('', views.Login_account.as_view(), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), 
    path("password_reset", views.password_reset_request, name="password_reset")
] 

zerowaste/models.py
from django.db import models
from django.core.files.base import ContentFile
from django.contrib.auth.models import User

# Create your models here.

class post(models.Model):
    post_title = models.CharField(max_length=200, verbose_name='商品名')
    post_image = models.ImageField(upload_to='media/', verbose_name='写真')
    post_price = models.PositiveIntegerField(verbose_name='値段')
    post_address = models.CharField(max_length=200,verbose_name='住所')
    post_date = models.DateTimeField('投稿日時', auto_now_add=True)

    def __str__(self):
        return self.post_title

zerowaste/forms.py
from django import forms
from django.forms import fields
from .models import post
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['username'].widget.attrs['class'] = 'form-group'
        self.fields['password1'].widget.attrs['class'] = 'form-group'
        self.fields['password2'].widget.attrs['class'] = 'form-group'

    class Meta:
       model = User
       fields = ("username", "password1", "password2",)

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = post
        fields = '__all__'

zerowaste/views.py
from django.http import request
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from .models import post
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from .forms import PostCreateForm, LoginForm, UserCreateForm
from django.views import View
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

class ListView(generic.ListView):
    model = post

class CreateView(generic.CreateView):
    model = post
    form_class = PostCreateForm
    success_url = reverse_lazy('zerowaste:index')

class Create_account(generic.CreateView):
    def post(self, request, *args, **kwargs):
        form = UserCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            #フォームから'username'を読み取る
            username = form.cleaned_data.get('username')
            #フォームから'password1'を読み取る
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
        return render(request, 'zerowaste/create.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = UserCreateForm(request.POST)
        return  render(request, 'zerowaste/create.html', {'form': form,})
create_account = Create_account.as_view()

class Login_account(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('/index')
        return render(request, 'zerowaste/login.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'zerowaste/login.html', {'form': form,})

def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "zerowaste/password_reset_email.txt"
					c = {
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Zerowaste',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ("/password_reset/done/")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="zerowaste/password_reset.html", context={"password_reset_form":password_reset_form})

zerowaste/templates/zerowaste/create.html
{% extends "zerowaste/post_list.html" %}

{% block contents %} 
<div class="container py-5">
	<h1>新規会員登録</h1>
	<form method="POST" action="">
		{% csrf_token %}
		<!-- <label>ユーザーID</label>
		{{ form.username }}
		<label>パスワード</label>
		{{ form.password1 }}
		<label>パスワード(確認)</label>
		{{ form.password2 }}
		<button class="btn btn-primary my-3" type="submit">登録</button> -->
		<div class="form-group p-3">
            <p>{{ form.username.label }}：</p>
            {{ form.username }}
        </div>
        <div class="form-group p-3">
            <p>{{ form.password1.label }}：</p>
            {{ form.password1 }}
        </div>
        <div class="form-group p-3">
            <p>{{ form.password2.label }}：</p>
            {{ form.password2 }}
        </div>
		<button class="my-2 fadein fourth" type="submit">登録</button>
	</form>
	<p class="text-center">既に会員登録済みの方はこちらから<a href="{% url 'zerowaste:login' %}">ログイン</a></p>
</div>

{% endblock %}

zerowaste/templates/zerowaste/login.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'zerowaste/login.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Login Form -->
    <body>
        {% if form.errors  %}
        <p>ユーザーID, パスワードが一致しません．</p>
        {% endif %}
        <form method="POST" action="">
          <div class="title">
            <p class="py-3">Zerowaste</p>
          </div>
          {% csrf_token %}
          <label>ユーザーID</label>
          {{ form.username}}
          {{ form.username.errors }}
          <label>パスワード</label>
          {{ form.password}}
          {{ form.password.errors }}
          <button type="submit" class="fadein fourth">ログイン</button>
        </form>
    </body>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a href="{% url 'zerowaste:create_account' %}" class="underlineHover">新規会員登録はこちら</a>
      <a class="underlineHover" href="/password_reset">パスワードを忘れた方はこちら</a>
    </div>



    
  </div>
</div>

zerowaste/templates/zerowaste/password_reset.html
{% extends "zerowaste/post_list.html" %}

{% block contents %} 

{% load crispy_forms_tags %}          

<!--Reset Password-->
<div class="container p-5">
       <h2 class="font-weight-bold mt-3">パスワード変更</h2>
    <hr>
    <p>パスワードを忘れましたか？ 下記にあなたのメールアドレスを入力してください。パスワードを変更するための手続きをいたします。</p>
    <form method="POST">
        {% csrf_token %}
        {{ password_reset_form|crispy }}                    
        <button class="fadein fourth m-4" type="submit">メール送信</button>
    </form>
  </div> 

{% endblock %}

zerowaste/templates/zerowaste/password_reset_complete.html
{% extends "zerowaste/post_list.html" %}

{% block contents %} 
  
  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">パスワードの変更完了</h2>
		<hr>
        <p>パスワードの変更が完了いたしましたので、下記からログインしてください</p>                 
        <a href="/" class="fadein fourth m-4">ログイン</a>
    </div>

{% endblock %}

zerowaste/templates/zerowaste/password_reset_confirm.html
{% extends "zerowaste/post_list.html" %}

{% block contents %}

  {% load crispy_forms_tags %}  
  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">パスワード変更確認</h2>
		<hr>
        <p>新しいパスワードを入力してください</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="fadein fourth mt-4" type="submit">パスワード変更</button>
        </form>
    </div>

{% endblock %}

zerowaste/templates/zerowaste/password_reset_done.html
{% extends "zerowaste/post_list.html" %}

{% block contents %}

	<!--Password reset sent-->
	<div class="container p-5">
  	<h2 class="font-weight-bold mt-3">パスワードを変更するためのメールを送信いたしました</h2>
		<hr>
		<p>新しいパスワードを設定するためのメールを送信いたしました。先ほど、入力したメールアドレスの受診トレイをご確認ください。もしメールが来ていないなら先程、入力したメールアドレスが合っているか、迷惑フォルダを確認してください</p>
  	</div>

{% endblock %}

zerowaste/templates/zerowaste/post_form.html
{% extends 'zerowaste/post_list.html' %}
{% load static %}

{% block contents %}
<form action="" method="POST" enctype="multipart/form-data">
    <div class="container">
        <div class="form-group p-3">
            <p>{{ form.post_title.label }}：</p>
            {{ form.post_title }}
        </div>
        <div class="form-group p-3">
            <p>{{ form.post_price.label }}：</p>
            {{ form.post_price }}
        </div>
        <div class="form-group p-3">
            <p>{{ form.post_address.label }}：</p>
            {{ form.post_address }}
        </div>
        <div class="custom-file p-3">
            <p>{{ form.post_image.label }}：</p>
            {{ form.post_image }}
        </div>
        <button type="submit" class="my-2 fadein fourth">送信</button>
        <a href="{% url 'zerowaste:index' %}" class="my-2 fadein fourth">ホームへ戻る</a>
    </div>
        
{% csrf_token %}
</form>
{% endblock %}

zerowaste/templates/zerowaste/post_list.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Zerowaste</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'zerowaste/style.css' %}">
    <link rel="stylesheet" href="{% static 'zerowaste/login.css' %}">
  </head>

  <body>

    <header>
      <div class="navbar navbar-dark color">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'zerowaste:index' %}" class="navbar-brand d-flex align-items-center">
            <strong>Zerowaste</strong>
          </a>
          <div class="login-form">
            {% if user.id %}
            <p>こんにちは、{{ user.username }}さん</p>
            <a class="btn-default mx-3" href="{% url 'zerowaste:logout' %}">ログアウト</a>
            {% else %}
            <a href="{% url 'zerowaste:login' %}" class="btn-default mx-3">ログイン</a>
            <a href="{% url 'zerowaste:create_account' %}" class="btn-default mx-3">アカウント作成</a>
            {% endif %}
          </div>
        </div>
      </div>
    </header>
    <main role="main">
      <section class="jumbotron text-center py-5">
        <div class="container">
          <h1 class="jumbotron-heading">Zerowaste</h1>
          <p class="lead text-muted">食料が余っている人と食料を求めている人のマッチングプラットフォームです。</p>
        </div>
      </section>
      {% block contents %}
      <div class="album py-5 bg-light">
        <div class="container">
          <p class="d-flex justify-content-center"><a href="{% url 'zerowaste:add' %}" class="my-2 fadein fourth">新規投稿</a></p>
          <div class="row">
            {% for post in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="thumbnail bg-black">
                  <img class="img-fluid center-block" src="{{ post.post_image.url }}" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">{{ post.post_title }}</p>
                  <p class="card-text">{{ post.post_price }}円</p>
                  <p class="card-text">{{ post.post_address }}</p>
                  <p class="card-text">{{ post.post_date }}</p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      {% endblock %}
    </main>
    <footer class="text-muted">
      <div class="container text-center">
        <p>zerowaste -All rights reserved-</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>